### ISSUE TITLE
Add a Meetup.com logo and link to the homepage with the other logos.

### ISSUE THREAD

**Issue by jcsmileyjr** [codeconnector/codeconnector.github.io#111]
The issue is that most of our events can be found via Meetup.com but it's not represented on our homepage. Our events are lumped together with our parent organization the Memphis Technology Foundation. 

I would like for the Meetup.com logo to be place near the Slack logo with this link: https://www.meetup.com/memphis-technology-user-groups/. 

Here is a logo to use or you can find a better one. 
![Meetup_Logo](https://github.com/codeconnector/codeconnector.github.io/assets/19346770/23243998-cccf-4405-a702-f07311690e11)

**Comment by nekablair** [comment]
I'd love to contribute to this issue.

**Comment by jcsmileyjr** [comment]
@nekablair I have assigned this to you .

**Comment by nekablair** [comment]
May I close this issue since the PR was approved and merged?

**Comment by jcsmileyjr** [comment]
Yes
