### ISSUE TITLE
Update the site to list meetup.com as the primary means of learning about upcoming events.

### ISSUE THREAD

**Issue by jcsmileyjr** [codeconnector/codeconnector.github.io#116]
The site currently lists Facebook and Eventbrite as the Code Connector primary means of listing upcoming events. Neither of these has been used in years. This should be changed to meetup.com with an explanation of our relationship under the Memphis Technology User Groups umbrella.

![cc-meetups-issues](https://github.com/codeconnector/codeconnector.github.io/assets/19346770/5b4de502-7e05-4416-bab5-3ea1cbcb5449)

**Comment by heysolomon** [comment]
@jcsmileyjr I would love to work on this.

**Comment by jcsmileyjr** [comment]
@heysolomon  Go for it.
