### ISSUE TITLE
Add Meetup link for upcoming events

### ISSUE THREAD

**Issue by Canfry** [codeconnector/codeconnector.github.io#117]
On Slack regarding upcoming events, I was redirectd to the Meetup webpage to participate to upcoming event. It will be nice to add the link to "Meetup" in the section "Upcoming events" in the learn.html file.

**Comment by nekablair** [comment]
Would love to help with this.

**Comment by jcsmileyjr** [comment]
Build it

**Comment by nekablair** [comment]
It doesn't look like I can assign myself.

**Comment by nekablair** [comment]
Thanks RJ!

**Comment by nekablair** [comment]
Unless I'm missing something, seems this issue has been handled already?

**Comment by jcsmileyjr** [comment]
I agree, it does seem like its done. I will mark it as fixed.

**Comment by jcsmileyjr** [comment]
This is completed.
