### ISSUE TITLE
[SEO] Links do not have descriptive text

### ISSUE THREAD

**Issue by rjbeers** [codeconnector/codeconnector.github.io#21]
According to [this lighthouse report](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fcodeconnector.io%2F#seo), several links are using generic link text. See https://web.dev/link-text/ for details on the issue and how to resolve it.

**Comment by readyready15728** [comment]
Setting up alt attributes for "CodeCrew" and "knoxdevs" (alternatively "knoxdevs.com") should also be done but that's kind of a no-brainer.

**Comment by rjbeers** [comment]
The alt tag issues are documented in #22. Care to open a pull request to fix this and possibly that issue as well?

**Comment by tjsutton11** [comment]
I'd like to be assigned this issue if that's okay!
