### ISSUE TITLE
[a11y] aria-* attributes do not have valid values

### ISSUE THREAD

**Issue by rjbeers** [codeconnector/codeconnector.github.io#28]
According to this [lighthouse report](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fcodeconnector.io%2F#accessibility), there are elements not specifying proper aria attributes.

More details on the topic can be found on [web.dev](https://web.dev/aria-valid-attr-value/).

>Assistive technologies, like screen readers, can't interpret ARIA attributes with invalid values.

**Comment by moody2times** [comment]
Please, can you give further details? I will like to help with fixing any accessibility issues on this project. So, please let me know.

**Comment by moody2times** [comment]
I used the firefox accessibility-inspector on the project and found massive accessibility issues of different kinds on some of the pages, eg /sponsor, /volunteer, and /about. See a snapshot 
![codeconnector-about](https://user-images.githubusercontent.com/64225540/95905530-e39b7580-0d90-11eb-9cce-a57799ef10fb.png)

There are keyboard issues, contrast issues, and text label issues that I can fix if you let me. I can fix them one by one. So, if you give details of the specific element you are referring to in this issue, I can start from there.

**Comment by rjbeers** [comment]
It seems that this issue was resolved in earlier code changes, but was never closed. I'm closing it now.

@moody2times I have not run accessibility tests on other pages. It seems you've found some issues. We'd appreciate any fixes you are willing to open a PR for.

**Comment by moody2times** [comment]
Alright then
