### ISSUE TITLE
Deduplicate header/footer code for maintainability

### ISSUE THREAD

**Issue by rjbeers** [codeconnector/codeconnector.github.io#34]
On most pages of the site, the header and footer are the same code or could easily be templated and reused. Instead, a change must be made in many places. How about we convert this site to use a static site generator like [Gatsby](https://www.gatsbyjs.org/), [Jekyll](https://jekyllrb.com/), [Hugo](https://gohugo.io/), or [11ty](https://www.11ty.dev/)?

**Comment by tedjpatterson** [comment]
Sounds like a healthy, logical move to me!

**Comment by rjbeers** [comment]
I think Gatsby would result in the fastest page load times, and also the most complicated code base. I think we should avoid it for the sake of keeping this repository open to everyone contributing.

**Comment by rjbeers** [comment]
This is resolved now that we use a static site generator.
